name: Update README

on:
  pull_request:
    types:
      - closed
  schedule:
    - cron: '0 5 * * 1'
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}